### ISSUE TITLE
b站视频中拉流用的videoplayer

### ISSUE THREAD

**Issue by zhjygit** [icetd/RkYoloRtspServer#2]
https://www.bilibili.com/video/BV1Ys421G7Hz/?spm_id_from=333.880.my_history.page.click&vd_source=3f50d71954b449d49920bf6ebb0eacbc
视频里面推流和拉流延迟较低，实测（vlc或ffplayer命令行拉流）有1秒的延迟，能否分享一下拉流的链接或地址。我的邮箱是djstmail@163.com
谢谢师傅了。

**Comment by icetd** [comment]
https://github.com/icetd/VideoPlayer
